apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  name: db-net-policy
  namespace: db-ns
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  podSelector:
    matchLabels:
      app: mongodb
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              app: backend #namespace of backend
      ports:
        - protocol: TCP
          port: 27017 #mongodb connection port