apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-ss
  namespace: db-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb-service #add this as an env for backend pods
  template:
    metadata:
      name: mongodb-pod
      labels:
        app: mongodb
    spec:
      serviceAccountName: db_secret_sa
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
      affinity:
        podAntiAffinity:  # Use anti-affinity to spread replicas
          preferredDuringSchedulingIgnoredDuringExecution: #make it preferred to allow scheduling for first pod
            - weight: 100
              podAffinityTerm:
                topologyKey: topology.kubernetes.io/zone
                labelSelector:
                  matchLabels:
                    app: mongodb
      containers:
        - name: mongodb-container
          image: mongodb/mongodb-community-server:7.0.1
          ports:
            - containerPort: 27017
          env:
            - name: POD_NAME  # ADD THIS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db_secret
                  key: username
                  
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db_secret
                  key: password
            - name: MONGODB_ADVERTISED_HOSTNAME
              value: "$(POD_NAME).mongodb-service.db-ns.svc.cluster.local"
          
          volumeMounts:
            - name: data-volume
              mountPath: /data/db
            - name: secrets_store
              mountPath: "/mnt/secrets-store"
              readOnly: true
          livenessProbe:
            exec:
              command: ["mongosh", "--eval", "db.adminCommand('ping')"]
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            exec:
              command: ["mongosh", "--eval", "db.adminCommand('ping')"]
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: secrets_store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: db_secrets
  volumeClaimTemplates:
    - metadata:
        name: data-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ebs-sc
        resources:
          requests:
            storage: 1Gi
      