apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: db-ns
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  MONGO_USERNAME: YWRtaW4=  # base64-encoded "admin"
  MONGO_PASSWORD: cGFzc3dvcmQ=  # base64-encoded "password"
