apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: db-ns
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  clusterIP: None  # Headless Service
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
    name: mongodb