apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: front-ns
  labels:
    service: front
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    app: front
  ports:
    - port: 8080
  type: ClusterIP #internal service and adding load balancing
  