apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/jenkins-data
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain

